#include "Debug/DebugType.h"

DEFINE_LOG_CATEGORY(DLogDefault);
DEFINE_LOG_CATEGORY(DLogManager);
DEFINE_LOG_CATEGORY(DLogProcedure);
DEFINE_LOG_CATEGORY(DLogUI);
DEFINE_LOG_CATEGORY(DLogCamera);
DEFINE_LOG_CATEGORY(DLogWorld);
DEFINE_LOG_CATEGORY(DLogProperty);
DEFINE_LOG_CATEGORY(DLogGameSetting);
