#include "Debug/DebugType.h"

DEFINE_LOG_CATEGORY(LogDefault);
DEFINE_LOG_CATEGORY(LogManager);
DEFINE_LOG_CATEGORY(LogProcedure);
DEFINE_LOG_CATEGORY(LogUI);
DEFINE_LOG_CATEGORY(LogCamera);
DEFINE_LOG_CATEGORY(LogWorld);
DEFINE_LOG_CATEGORY(LogProperty);
DEFINE_LOG_CATEGORY(LogGameSetting);
