// Copyright ChenTaiye 2025. All Rights Reserved. 

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"
#include "Kismet/GameplayStatics.h"
// #include "GenericType.generated.h"

#define BROADCAST_UNIFIED_DELEGATE(DelegateName, BPDelegateName, ...) \
	DelegateName.Broadcast(__VA_ARGS__); \
	BPDelegateName.Broadcast(__VA_ARGS__);

UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result);

UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_Success);
UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_Fail);
UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_Retry);

UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_Yes);
UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_YesAll);
UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_No);
UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_NoAll);
UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_Continue);
UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_Cancel);

// UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event);
// UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Hovered);
// UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Unhovered);
// UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Pressed);
// UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Released);
// UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Clicked);
// UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_TouchBegin);
// UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_TouchEnd);
// UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_TouchDragBegin);
// UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_TouchDragEnd);
