// Copyright ChenTaiye 2025. All Rights Reserved. 

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"
// #include "GenericType.generated.h"

UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result);

UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_Success);
UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_Fail);
UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_Retry);

UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_Yes);
UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_YesAll);
UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_No);
UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_NoAll);
UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_Continue);
UNREALMISC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Result_Cancel);
