#include "K2Node/FBlueprintGraphPanelPinExtendFactory.h"

#include "SGraphPinDataTableRowName.h"
#include "K2Node/K2Node_ProcessEvent.h"
#include "Kismet2/BlueprintEditorUtils.h"

TSharedPtr<SGraphPin> FBlueprintGraphPanelPinExtendFactory::CreatePin(UEdGraphPin* Pin) const
{
	if (Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Name)
	{
		UObject* Outer = Pin->GetOuter();

		const UEdGraphPin* TargetPin = nullptr;
		if (Outer->IsA(UK2Node_ProcessEvent::StaticClass()))
		{
			const UK2Node_ProcessEvent* ProcessEventNode = CastChecked<UK2Node_ProcessEvent>(Outer);
			TargetPin = ProcessEventNode->GetTargetPin();
		}

		if (TargetPin)
		{
			if (TargetPin->LinkedTo.Num() != 0)
			{
				UEdGraphPin* LinkedPin = TargetPin->LinkedTo[0];
				TWeakObjectPtr<UObject> ObjectPtr = LinkedPin->PinType.PinSubCategoryObject;
				if (ObjectPtr.IsValid())
				{
					const UClass* Class = Cast<UClass>(ObjectPtr);
					const UObject* ClassDefaultObject = nullptr;
					const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>();

					UFunction* Function;
					if (Class)
					{
						Function = Class->FindFunctionByName(FName(Pin->DefaultValue));
						ClassDefaultObject = Class->GetDefaultObject(false);
					}
					else
					{
						Function = ObjectPtr->FindFunction(FName(Pin->DefaultValue));
						ClassDefaultObject = ObjectPtr->GetClass()->GetDefaultObject();
					}

					for (TFieldIterator<FProperty> It(Function); It; ++It)
					{
						FProperty* Property = *It;
						UEdGraphPin* PropertyPin = Pin->GetOwningNode()->FindPin(Property->GetFName());
						FStructOnScope StructOnScope(It.GetStruct());

						if (Property->HasAnyPropertyFlags(CPF_Parm) &&
							Property->HasAllPropertyFlags(CPF_BlueprintVisible) &&
							!PropertyPin)
						{
							if (UEdGraphPin* NewPropertyPin = Pin->GetOwningNode()->CreatePin(EGPD_Input, NAME_None, Property->GetFName()))
							{
								K2Schema->ConvertPropertyToPinType(Property, NewPropertyPin->PinType);

								if (ClassDefaultObject && K2Schema->PinDefaultValueIsEditable(*NewPropertyPin))
								{
									FString DefaultValueAsString;
									const bool bDefaultValueSet = FBlueprintEditorUtils::PropertyValueToString(Property, StructOnScope.GetStructMemory(), DefaultValueAsString, Pin->GetOwningNode());
									check(bDefaultValueSet);
									K2Schema->SetPinAutogeneratedDefaultValue(NewPropertyPin, DefaultValueAsString);
								}

								// Copy tooltip from the property.
								K2Schema->ConstructBasicPinTooltip(*NewPropertyPin, Property->GetToolTipText(), NewPropertyPin->PinToolTip);
							}
						}
					}

					return SNew(SGraphPinNameList, Pin, GetObjectFunctionNames(ObjectPtr.Get()));
				}
			}
		}
	}

	return nullptr;
}

TArray<TSharedPtr<FName>> FBlueprintGraphPanelPinExtendFactory::GetObjectFunctionNames(UObject* InObject) const
{
	TArray<TSharedPtr<FName>> RowNames;

	const UClass* Class = Cast<UClass>(InObject);
	if (!Class)
	{
		Class = InObject->GetClass();
	}

	for (TFieldIterator<UFunction> It(Class); It; ++It)
	{
		if (It->FunctionFlags & (FUNC_BlueprintCallable | FUNC_BlueprintPure))
		{
			TSharedPtr<FName> RowNameItem = MakeShareable(new FName(It->GetName()));
			RowNames.Add(RowNameItem);
		}
	}

	return RowNames;
}
